config/routes.rb
Rails.application.routes.draw do
  resources :xp_entries
  resources :characters
  resources :players
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :player
  has_many :xp_entries, dependent: :destroy

  def xp
    xp_entries.sum(:amount)
  end
end

app/models/player.rb
class Player < ApplicationRecord
    has_many :characters, dependent: :destroy
end

app/models/xp_entry.rb
class XpEntry < ApplicationRecord
  belongs_to :player
  belongs_to :character
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def character_params
      params.require(:character).permit(:player_id, :name, :xp)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:name)
    end
end

app/controllers/xp_entries_controller.rb
class XpEntriesController < ApplicationController
  before_action :set_xp_entry, only: [:show, :edit, :update, :destroy]

  # GET /xp_entries
  # GET /xp_entries.json
  def index
    @xp_entries = XpEntry.all
  end

  # GET /xp_entries/1
  # GET /xp_entries/1.json
  def show
  end

  # GET /xp_entries/new
  def new
    @xp_entry = XpEntry.new
  end

  # GET /xp_entries/1/edit
  def edit
  end

  # POST /xp_entries
  # POST /xp_entries.json
  def create
    @xp_entry = XpEntry.new(xp_entry_params)

    respond_to do |format|
      if @xp_entry.save
        format.html { redirect_to @xp_entry, notice: 'Xp entry was successfully created.' }
        format.json { render :show, status: :created, location: @xp_entry }
      else
        format.html { render :new }
        format.json { render json: @xp_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /xp_entries/1
  # PATCH/PUT /xp_entries/1.json
  def update
    respond_to do |format|
      if @xp_entry.update(xp_entry_params)
        format.html { redirect_to @xp_entry, notice: 'Xp entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @xp_entry }
      else
        format.html { render :edit }
        format.json { render json: @xp_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /xp_entries/1
  # DELETE /xp_entries/1.json
  def destroy
    @xp_entry.destroy
    respond_to do |format|
      format.html { redirect_to xp_entries_url, notice: 'Xp entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_xp_entry
      @xp_entry = XpEntry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def xp_entry_params
      params.require(:xp_entry).permit(:amount, :player_id, :character_id, :audited)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/xp_entries_helper.rb
module XpEntriesHelper
end

app/views/characters/_form.html.erb
  <%= form_with(model: character, local: true, class: "ui form") do |form| %>
    <% if character.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

        <ul>
          <% character.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
        <%= form.label :player %>
       <%= form.collection_select :player_id,
        Player.order(:name),:id,:name, { include_blank: true } %>
    </div>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="actions">
      <%= form.submit class: "ui button" %>
    </div>
  <% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
  <p id="notice"><%= notice %></p>

  <h1>Characters</h1>

  <table class="ui celled table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Player</th>
        <th>XP</th>
      </tr>
    </thead>

    <tbody>
      <% @characters.each do |character| %>
        <tr>
          <td><%= link_to character.name, character %></td>
          <td><%= link_to character.player.name, character.player %></td>
          <td><%= character.xp %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
  <p id="notice"><%= notice %></p>

  <h1><%= @character.name %></h1>

  <p>
    <strong>Player:</strong>
    <%= @character.player.name %>
  </p>

  <p>
    <strong>XP:</strong>
    <%= @character.xp %>
  </p>

  <table class="ui celled table">
    <thead>
      <tr>
        <th>Amount</th>
        <th>Player</th>
        <th>Comment</th>
      </tr>
    </thead>

    <tbody>
      <% @character.xp_entries.each do |entry| %>
        <tr>
          <td><%= entry.amount %></td>
          <td><%= entry.player %></td>
          <td><%= entry.comment %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Back', characters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ledger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
  <p id="notice"><%= notice %></p>

  <h1>Players</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @players.each do |player| %>
        <tr>
          <td><%= player.name %></td>
          <td><%= link_to 'Show', player %></td>
          <td><%= link_to 'Edit', edit_player_path(player) %></td>
          <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
  <h1>New Player</h1>

  <%= render 'form', player: @player %>

  <%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/xp_entries/_form.html.erb
<%= form_with(model: xp_entry, local: true) do |form| %>
  <% if xp_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(xp_entry.errors.count, "error") %> prohibited this xp_entry from being saved:</h2>

      <ul>
        <% xp_entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :player_id %>
    <%= form.text_field :player_id %>
  </div>

  <div class="field">
    <%= form.label :character_id %>
    <%= form.text_field :character_id %>
  </div>

  <div class="field">
    <%= form.label :audited %>
    <%= form.check_box :audited %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/xp_entries/edit.html.erb
<h1>Editing Xp Entry</h1>

<%= render 'form', xp_entry: @xp_entry %>

<%= link_to 'Show', @xp_entry %> |
<%= link_to 'Back', xp_entries_path %>

app/views/xp_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Xp Entries</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Player</th>
      <th>Character</th>
      <th>Audited</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @xp_entries.each do |xp_entry| %>
      <tr>
        <td><%= xp_entry.amount %></td>
        <td><%= xp_entry.player_id %></td>
        <td><%= xp_entry.character_id %></td>
        <td><%= xp_entry.audited %></td>
        <td><%= link_to 'Show', xp_entry %></td>
        <td><%= link_to 'Edit', edit_xp_entry_path(xp_entry) %></td>
        <td><%= link_to 'Destroy', xp_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Xp Entry', new_xp_entry_path %>

app/views/xp_entries/new.html.erb
<h1>New Xp Entry</h1>

<%= render 'form', xp_entry: @xp_entry %>

<%= link_to 'Back', xp_entries_path %>

app/views/xp_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @xp_entry.amount %>
</p>

<p>
  <strong>Player:</strong>
  <%= @xp_entry.player_id %>
</p>

<p>
  <strong>Character:</strong>
  <%= @xp_entry.character_id %>
</p>

<p>
  <strong>Audited:</strong>
  <%= @xp_entry.audited %>
</p>

<%= link_to 'Edit', edit_xp_entry_path(@xp_entry) %> |
<%= link_to 'Back', xp_entries_path %>